### PR TITLE
Updated pull request

### PR DESCRIPTION
**Pull request by OscarRousham**
Hi, 
Update the pull request to remove the old unused scripts/files. Also update .gitignore the the readME files.

Thanks.

### CODE REVIEW

**Comment by RobertASmith** [comment]
Hi Oscar,

Unfortunately this still doesn't work.

1) When running `clean_parkrun_data.R` I get this error:

image.

I suspect this is because you've not pushed the raw data to the repo.

2) The README.md file is not sufficiently detailed to replicate the analysis.
- What does this repository relate to? How would someone know they are in the right place. I generally insert the title, authors + abstract at the top.
- Two scripts are given but there are no scripts in the directory, I know they are both in `scripts` but the reader may not know what they are doing.
- How would they access the project, for example in the DoPE project we had:

image



```
# parkrun_temporal_23

Code to assess the long-term impact of the pandemic on parkrun participation.

Run the scripts in the following order:
1. Clean_parkrun_data: cleans raw data files, outputs datasets ready for analysis.
2. time_series: runs descriptive and statistical analyses.

```

**Comment by OscarRousham** [comment]
Hi Rob, 

I haven't pushed the raw data to the repo as I wasn't sure of the permissions re making this data public (the repo is public I believe). Happy to push these if that is allowed.

Good point making the  readME instructions more comprehensive - I will update this now.  I will also include the title/authors/abstract once we have finalised these.

**Comment by RobertASmith** [comment]
Ahh I see, so:

I haven't pushed the raw data to the repo as I wasn't sure of the
permissions re making this data public (the repo is public I believe).
Happy to push these if that is allowed.
- yeah so if there are concerns about permissions then users need to know
exactly how to get the data and where to put this. This should be included
in the readme. In the last repo we just used included the data for
simplicity (think the data is publicly available anyway right?) but I
completely understand you may not want to do this.


Good point making the readME instructions more comprehensive - I will
update this now. I will also include the title/authors/abstract once we
have finalised these.

Other examples (these are ones I've made, you may want to look for better
ones too):
- dark-peak-analytics/HECONpack: Example R package for a health economic
model (github.com) <https://github.com/dark-peak-analytics/HECONpack>
- dark-peak-analytics/plumberHE: Health Economics using Plumber APIs
(github.com) <https://github.com/dark-peak-analytics/plumberHE/tree/main>
- RobertASmith/HEAT_DRF: Is it feasible to adapt the HEAT model to
incorporate PA distributions and DRFs (github.com)
<https://github.com/RobertASmith/HEAT_DRF>
- ukhsa-collaboration/UKHSA_Immensa_analysis (github.com)
<https://github.com/ukhsa-collaboration/UKHSA_Immensa_analysis>

**Comment by RobertASmith** [comment]
Hi @OscarRousham,

Just checking if you've been able to provide a summary of how a reviewer can access the data including:
- where to get the data required from?
- where to store the required data?
- in what format to store the required data?
...

Otherwise nobody will be able to reproduce the analysis.

Cheers,

Rob

**Comment by OscarRousham** [comment]
Pull request updated to include datasets to carry out analysis, updated README to reflect this and tidied up the code.

**Review by RobertASmith — APPROVED** [review]
Hi Oscar, 

Thanks for this. There are some edits which I'll do after merge. 

Almost there.

Kind regards,

Rob

**Pull request merged**
